poseReference:
  - 0.7
  - 0.0
  - 0.5
  - 0
  - 1.57
  - 0
radiusObject: 0.1
radiusTrajectory: 0.5

trajectoryStepsSize: 0.05
trajectoryStepsNumber: 10
trajectoryAxis: [1,0,0]

distanceToObject: 0.05